name: Scrape Marantec Jobs

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule (every day at 05:00 UTC)
  schedule:
    - cron: '0 5 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v3

      # Sets up python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Runs the scraper script
      - name: Run Python Scraper
        run: python scraper.py

      # Commits the changes to jobs.json back to the repository
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Updated job listings"
          file_pattern: "jobs.json"

